# Generated by Django 3.0.8 on 2020-08-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200815_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='actualBid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
