# Generated by Django 3.0.8 on 2020-08-16 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200816_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='caract',
        ),
        migrations.AddField(
            model_name='characteristic',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='auctions.Listing'),
            preserve_default=False,
        ),
    ]
