# Generated by Django 3.0.8 on 2020-08-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200816_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='urlImage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
